spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
    schemas: public
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: catalog-service
server:
  port: 8080
  error:
    include-message: always